// Unit tests for the CSRF PoC generator (web/src/components/csrf.ts).
// Run:  node web/test/csrf.test.ts   (Node >= 22.18 strips types natively)
import assert from 'node:assert/strict'
import { generateCsrfPoc, parseUrlencoded } from '../src/components/csrf.ts'
import type { Header } from '../src/types.ts'

let passed = 0
const ok = (name: string, fn: () => void) => {
  try {
    fn()
    passed++
    console.log(`  ✓ ${name}`)
  } catch (e) {
    console.error(`  ✗ ${name}`)
    throw e
  }
}

const h = (...pairs: [string, string][]): Header[] => pairs.map(([name, value]) => ({ name, value }))
const BASE = { autoSubmit: true, submitButton: false } as const

// ---- POST, urlencoded: the canonical Burp form PoC ----
ok('POST urlencoded → auto-submitting form with hidden inputs', () => {
  const poc = generateCsrfPoc(
    {
      method: 'POST',
      url: 'https://example.com/my-account/change-email',
      headers: h(['Content-Type', 'application/x-www-form-urlencoded']),
      bodyText: 'email=evil@gracefulsecurity.com',
    },
    { technique: 'auto', ...BASE },
  )
  assert.equal(poc.used, 'form')
  assert.equal(poc.warnings.length, 0)
  assert.match(poc.html, /<!-- CSRF PoC - generated by Pulse -->/)
  assert.match(poc.html, /<script>history\.pushState\('', '', '\/'\)<\/script>/)
  assert.match(poc.html, /<form action="https:\/\/example\.com\/my-account\/change-email" method="POST">/)
  assert.match(poc.html, /<input type="hidden" name="email" value="evil@gracefulsecurity\.com" \/>/)
  assert.match(poc.html, /document\.forms\[0\]\.submit\(\);/)
  // no cookies in the PoC — the victim's browser adds them
  assert.ok(!/cookie/i.test(poc.html))
})

ok('POST urlencoded with several params keeps order and decodes', () => {
  const poc = generateCsrfPoc(
    {
      method: 'POST',
      url: 'https://a.io/transfer',
      headers: h(['Content-Type', 'application/x-www-form-urlencoded']),
      bodyText: 'to=alice&amount=100&note=hi+there&msg=a%3Db%26c',
    },
    { technique: 'auto', ...BASE },
  )
  const inputs = poc.html.match(/<input type="hidden"[^>]+>/g) ?? []
  assert.equal(inputs.length, 4)
  assert.match(inputs[0]!, /name="to" value="alice"/)
  assert.match(inputs[2]!, /name="note" value="hi there"/)
  assert.match(inputs[3]!, /name="msg" value="a=b&amp;c"/) // decoded, then HTML-escaped
})

ok('POST with no Content-Type is still treated as form data', () => {
  const poc = generateCsrfPoc({ method: 'POST', url: 'https://a.io/x', headers: [], bodyText: 'a=1' }, { technique: 'auto', ...BASE })
  assert.equal(poc.used, 'form')
  assert.match(poc.html, /name="a" value="1"/)
})

// ---- GET: query params become hidden inputs, no method attr ----
ok('GET with query → form without method attr, query as inputs', () => {
  const poc = generateCsrfPoc(
    { method: 'GET', url: 'https://example.com/search?q=pulse&page=2', headers: [], bodyText: '' },
    { technique: 'auto', ...BASE },
  )
  assert.equal(poc.used, 'form')
  assert.equal(poc.warnings.length, 0)
  assert.match(poc.html, /<form action="https:\/\/example\.com\/search">/)
  assert.ok(!/method="/.test(poc.html))
  assert.match(poc.html, /name="q" value="pulse"/)
  assert.match(poc.html, /name="page" value="2"/)
})

// ---- HTML escaping ----
ok('attribute values are HTML-escaped', () => {
  const poc = generateCsrfPoc(
    {
      method: 'POST',
      url: 'https://a.io/x?a=<b>"',
      headers: h(['Content-Type', 'application/x-www-form-urlencoded']),
      bodyText: 'x=<script>"\'',
    },
    { technique: 'auto', ...BASE },
  )
  assert.ok(!poc.html.includes('value="<script>'))
  assert.match(poc.html, /value="&lt;script&gt;&quot;&#39;"/)
})

// ---- options ----
ok('autoSubmit off drops the submit script', () => {
  const poc = generateCsrfPoc(
    { method: 'POST', url: 'https://a.io/x', headers: h(['Content-Type', 'application/x-www-form-urlencoded']), bodyText: 'a=1' },
    { technique: 'auto', autoSubmit: false, submitButton: false },
  )
  assert.ok(!poc.html.includes('document.forms[0].submit()'))
})

ok('submitButton on adds the manual button (Burp label)', () => {
  const poc = generateCsrfPoc(
    { method: 'POST', url: 'https://a.io/x', headers: h(['Content-Type', 'application/x-www-form-urlencoded']), bodyText: 'a=1' },
    { technique: 'auto', autoSubmit: false, submitButton: true },
  )
  assert.match(poc.html, /<input type="submit" value="Submit request" \/>/)
  assert.ok(poc.html.indexOf('<input type="submit"') > poc.html.indexOf('name="a"'))
})

// ---- JSON → XHR in auto ----
ok('POST JSON → XHR technique with exact content type, body and credentials', () => {
  const poc = generateCsrfPoc(
    {
      method: 'POST',
      url: 'https://example.com/api/login',
      headers: h(['Content-Type', 'application/json; charset=utf-8']),
      bodyText: '{"username":"wiener","password":"peter"}',
    },
    { technique: 'auto', ...BASE },
  )
  assert.equal(poc.used, 'xhr')
  assert.match(poc.html, /var xhr = new XMLHttpRequest\(\);/)
  assert.match(poc.html, /xhr\.open\("POST", "https:\/\/example\.com\/api\/login", true\);/)
  assert.match(poc.html, /xhr\.setRequestHeader\('Content-Type', "application\/json; charset=utf-8"\);/)
  assert.match(poc.html, /xhr\.withCredentials = true;/)
  assert.match(poc.html, /xhr\.send\("\{\\"username\\":\\"wiener\\",\\"password\\":\\"peter\\"\}"\);/)
  assert.ok(poc.warnings.length > 0, 'preflight warning expected')
})

ok('JSON forced through the form technique uses the text/plain split trick', () => {
  const poc = generateCsrfPoc(
    {
      method: 'POST',
      url: 'https://example.com/api',
      headers: h(['Content-Type', 'application/json']),
      bodyText: '{"a":"b=c"}',
    },
    { technique: 'form', ...BASE },
  )
  assert.equal(poc.used, 'form')
  assert.match(poc.html, /enctype="text\/plain"/)
  // name + "=" + value must reassemble the exact JSON body
  const m = poc.html.match(/<input type="hidden" name="([\s\S]*?)" value="([\s\S]*?)" \/>/)
  assert.ok(m, 'hidden input present')
  const name = m[1]!.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;/g, "'")
  const value = m[2]!.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;/g, "'")
  assert.equal(`${name}=${value}`, '{"a":"b=c"}')
  assert.ok(poc.warnings.some((w) => w.includes('text/plain')))
})

ok('JSON without any = gets a dummy property injected for the split', () => {
  const poc = generateCsrfPoc(
    {
      method: 'POST',
      url: 'https://example.com/api',
      headers: h(['Content-Type', 'application/json']),
      bodyText: '{"username":"wiener"}',
    },
    { technique: 'form', ...BASE },
  )
  const m = poc.html.match(/<input type="hidden" name="([\s\S]*?)" value="([\s\S]*?)" \/>/)
  assert.ok(m)
  const unesc = (s: string) => s.replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;/g, "'")
  const sent = `${unesc(m[1]!)}=${unesc(m[2]!)}`
  assert.equal(sent, '{"username":"wiener","x":"="}')
  // …and the sent body is still valid JSON
  assert.equal(JSON.parse(sent).username, 'wiener')
})

ok('non-JSON body without = warns about inexact reproduction', () => {
  const poc = generateCsrfPoc(
    { method: 'POST', url: 'https://a.io/x', headers: h(['Content-Type', 'text/csv']), bodyText: 'a,b,c' },
    { technique: 'form', ...BASE },
  )
  assert.ok(poc.warnings.some((w) => w.includes('cannot be reproduced exactly')))
})

// ---- other methods ----
ok('PUT → XHR with method warning', () => {
  const poc = generateCsrfPoc(
    { method: 'PUT', url: 'https://a.io/api/1', headers: h(['Content-Type', 'application/json']), bodyText: '{"a":1}' },
    { technique: 'auto', ...BASE },
  )
  assert.equal(poc.used, 'xhr')
  assert.match(poc.html, /xhr\.open\("PUT"/)
})

ok('PUT forced through the form technique degrades to POST with a warning', () => {
  const poc = generateCsrfPoc(
    { method: 'PUT', url: 'https://a.io/api/1', headers: h(['Content-Type', 'application/json']), bodyText: '{"a":1}' },
    { technique: 'form', ...BASE },
  )
  assert.match(poc.html, /method="POST"/)
  assert.ok(poc.warnings.some((w) => w.includes('PUT')))
})

ok('multipart POST → XHR in auto (form cannot rebuild the boundary)', () => {
  const poc = generateCsrfPoc(
    {
      method: 'POST',
      url: 'https://a.io/up',
      headers: h(['Content-Type', 'multipart/form-data; boundary=XYZ']),
      bodyText: '--XYZ\r\nContent-Disposition: form-data; name="f"\r\n\r\nv\r\n--XYZ--\r\n',
    },
    { technique: 'auto', ...BASE },
  )
  assert.equal(poc.used, 'xhr')
  assert.match(poc.html, /multipart\/form-data; boundary=XYZ/)
})

ok('POST with query string keeps the query in the form action', () => {
  const poc = generateCsrfPoc(
    { method: 'POST', url: 'https://a.io/x?token=1', headers: h(['Content-Type', 'application/x-www-form-urlencoded']), bodyText: 'a=1' },
    { technique: 'auto', ...BASE },
  )
  assert.match(poc.html, /action="https:\/\/a\.io\/x\?token=1"/)
})

// ---- parseUrlencoded helper ----
ok('parseUrlencoded: order, empty values, lenient decoding', () => {
  assert.deepEqual(parseUrlencoded('a=1&b&c=x%20y&d=p+q'), [
    ['a', '1'],
    ['b', ''],
    ['c', 'x y'],
    ['d', 'p q'],
  ])
  assert.deepEqual(parseUrlencoded(''), [])
  // undecodable sequences survive verbatim
  assert.deepEqual(parseUrlencoded('k=%zz'), [['k', '%zz']])
})

console.log(`\n${passed} assertions groups passed`)
